name: Lint workflow

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install ruff
      - name: Lint (ruff check)
        run: ruff check proyectotfg tests
      - name: Format consistency (ruff format --check)
        run: ruff format --check proyectotfg tests
