name: Python tests workflow

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instala Poetry
        run: pipx install poetry

      - name: Instala las dependencias (incluye dev)
        run: |
          poetry install --with dev --no-interaction

      - name: Ejecuta pytest
        run: poetry run pytest -q
